sudo: false

language: node_js

node_js:
  - "8.5"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=test:dist
    - TEST_TYPE=test:lib
    - TEST_TYPE=test:es
    - TEST_TYPE=test:dom
    - TEST_TYPE=test:node

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    fi
